services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5

  selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome:4.1.2
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_PORT=5555
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSION=5
    volumes:
      - /dev/shm:/dev/shm

  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: fastapi_service
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer_service:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    container_name: consumer_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      selenium-hub:
        condition: service_started